name: Lint, Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Keep parallel runs from piling up on the same ref
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# Principle of least privilege for the default GITHUB_TOKEN
permissions:
  contents: read

jobs:
  spell:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup spell check
        uses: codespell-project/actions-codespell@v2

  format:
    name: Go Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up go version
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Check formatting (fail if changes needed)
        run: |
          set -e
          files="$(goimports -l .)"
          if [ -n "$files" ]; then
            echo "::error::The following files are not formatted:"
            echo "$files" | sed 's/^/- /'
            echo ""
            echo "Unified diff (what goimports would change):"
            goimports -d .
            exit 1
          fi
          echo "All Go files are properly formatted."

  build:
    name: Go Build, Vet & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
      - name: Build
        run: go build -v ./...
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -v ./...
