name: codespell

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  spell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup spell check
        uses: codespell-project/actions-codespell@v2
        with:
          path: .
          builtin: clear,rare
          check_filenames: true
          check_hidden: true
          ignore_words_file: .codespellignore
          only_warn: 1
