name: Format Go Code

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up go version
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Check formatting (fail if changes needed)
        run: |
          set -e
          files="$(goimports -l .)"
          if [ -n "$files" ]; then
            echo "::error::The following files are not formatted:"
            echo "$files" | sed 's/^/- /'
            echo ""
            echo "Unified diff (what goimports would change):"
            goimports -d .
            exit 1
          fi
          echo "All Go files are properly formatted."
