name: Format Go Code

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          persist-credentials: true
          fetch-depth: 0

      - name: Set up go version
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: go format
        run: gofmt -w .

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: format Go code via gofmt/goimports"
          git push origin HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
