name: Format Go Code

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up go version
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: go format
        run: goimports -w .

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: format Go code via gofmt/goimports"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
